In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("D:\\loan_predition\\data\\raw\\Loan Dataset.csv")
df.head()

,Applicant_ID,Gender,Age,Marital_Status,Dependents,Education,Employment_Status,Occupation_Type,Residential_Status,City/Town,...,Loan_Amount_Requested,Loan_Term,Loan_Purpose,Interest_Rate,Loan_Type,Co-Applicant,Bank_Account_History,Transaction_Frequency,Default_Risk,Loan_Approval_Status
0,1,Female,25,Married,2,Graduate,Employed,Business,Own,Urban,...,24535,209,Home,4.27,Secured,Yes,8,20,0.81,1
1,2,Male,36,Married,2,High School,Employed,Business,Own,Suburban,...,8288,33,Home,14.78,Unsecured,Yes,9,9,0.17,0
2,3,Male,43,Single,0,Postgraduate,Self-Employed,Freelancer,Own,Urban,...,10308,159,Vehicle,12.33,Secured,Yes,7,27,0.25,0
3,4,Female,28,Married,0,High School,Self-Employed,Freelancer,Rent,Suburban,...,33937,39,Personal,8.77,Secured,No,9,16,0.27,1
4,5,Female,32,Single,0,Graduate,Employed,Salaried,Rent,Suburban,...,23360,34,Home,9.04,Unsecured,No,1,17,0.32,1

In [6]:
df.columns

Index(['Applicant_ID', 'Gender', 'Age', 'Marital_Status', 'Dependents',
       'Education', 'Employment_Status', 'Occupation_Type',
       'Residential_Status', 'City/Town', 'Annual_Income', 'Monthly_Expenses',
       'Credit_Score', 'Existing_Loans', 'Total_Existing_Loan_Amount',
       'Outstanding_Debt', 'Loan_History', 'Loan_Amount_Requested',
       'Loan_Term', 'Loan_Purpose', 'Interest_Rate', 'Loan_Type',
       'Co-Applicant', 'Bank_Account_History', 'Transaction_Frequency',
       'Default_Risk', 'Loan_Approval_Status'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 52000 entries, 0 to 51999
Data columns (total 27 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Applicant_ID                52000 non-null  int64
 1   Gender                      52000 non-null  str
 2   Age                         52000 non-null  int64
 3   Marital_Status              52000 non-null  str
 4   Dependents                  52000 non-null  int64
 5   Education                   52000 non-null  str
 6   Employment_Status           52000 non-null  str
 7   Occupation_Type             52000 non-null  str
 8   Residential_Status          52000 non-null  str
 9   City/Town                   52000 non-null  str
 10  Annual_Income               52000 non-null  int64
 11  Monthly_Expenses            52000 non-null  int64
 12  Credit_Score                52000 non-null  int64
 13  Existing_Loans              52000 non-null  int64
 14  Total_Existing_Loan_Amount  52000 non-null  int64
 15  Outstanding_Debt            52000 non-null  int64
 16  Loan_History                52000 non-null  int64
 17  Loan_Amount_Requested       52000 non-null  int64
 18  Loan_Term                   52000 non-null  int64
 19  Loan_Purpose                52000 non-null  str
 20  Interest_Rate               52000 non-null  float64
 21  Loan_Type                   52000 non-null  str
 22  Co-Applicant                52000 non-null  str
 23  Bank_Account_History        52000 non-null  int64
 24  Transaction_Frequency       52000 non-null  int64
 25  Default_Risk                52000 non-null  float64
 26  Loan_Approval_Status        52000 non-null  int64
dtypes: float64(2), int64(15), str(10)
memory usage: 14.1 MB

In [8]:
df.describe()

,Applicant_ID,Age,Dependents,Annual_Income,Monthly_Expenses,Credit_Score,Existing_Loans,Total_Existing_Loan_Amount,Outstanding_Debt,Loan_History,Loan_Amount_Requested,Loan_Term,Interest_Rate,Bank_Account_History,Transaction_Frequency,Default_Risk,Loan_Approval_Status
count,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000
mean,26000.500000,38.898385,1.498000,83588.474404,2748.064885,678.089019,0.997865,24939.087962,14984.864923,0.198596,21102.765481,125.827019,9.253494,4.503923,17.031808,0.500204,0.641654
std,15011.251336,10.553928,1.118077,35720.851522,1295.678763,159.990367,0.815586,14407.886552,8663.404305,0.398947,8224.940906,65.509959,3.318356,2.872721,7.212011,0.289939,0.479519
min,1.000000,18.000000,0.000000,20009.000000,500.000000,300.000000,0.000000,0.000000,0.000000,0.000000,5000.000000,12.000000,3.500000,0.000000,5.000000,0.000000,0.000000
25%,13000.750000,31.000000,0.000000,55564.000000,1636.000000,553.000000,0.000000,12498.000000,7511.750000,0.000000,16941.750000,69.000000,6.400000,2.000000,11.000000,0.250000,0.000000
50%,26000.500000,38.000000,1.000000,78839.000000,2739.000000,742.000000,1.000000,24964.000000,14984.500000,0.000000,21039.000000,126.000000,9.240000,5.000000,17.000000,0.500000,1.000000
75%,39000.250000,45.000000,2.000000,114226.000000,3866.000000,796.000000,2.000000,37399.500000,22432.250000,0.000000,25809.000000,182.000000,12.140000,7.000000,23.000000,0.750000,1.000000
max,52000.000000,69.000000,3.000000,149998.000000,4999.000000,849.000000,2.000000,49999.000000,29998.000000,1.000000,44848.000000,239.000000,15.000000,9.000000,29.000000,1.000000,1.000000

In [9]:
df["Loan_Approval_Status"].value_counts()

Loan_Approval_Status
1    33366
0    18634
Name: count, dtype: int64

In [10]:
df.isnull().sum()

Applicant_ID                  0
Gender                        0
Age                           0
Marital_Status                0
Dependents                    0
Education                     0
Employment_Status             0
Occupation_Type               0
Residential_Status            0
City/Town                     0
Annual_Income                 0
Monthly_Expenses              0
Credit_Score                  0
Existing_Loans                0
Total_Existing_Loan_Amount    0
Outstanding_Debt              0
Loan_History                  0
Loan_Amount_Requested         0
Loan_Term                     0
Loan_Purpose                  0
Interest_Rate                 0
Loan_Type                     0
Co-Applicant                  0
Bank_Account_History          0
Transaction_Frequency         0
Default_Risk                  0
Loan_Approval_Status          0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.columns

Index(['Applicant_ID', 'Gender', 'Age', 'Marital_Status', 'Dependents',
       'Education', 'Employment_Status', 'Occupation_Type',
       'Residential_Status', 'City/Town', 'Annual_Income', 'Monthly_Expenses',
       'Credit_Score', 'Existing_Loans', 'Total_Existing_Loan_Amount',
       'Outstanding_Debt', 'Loan_History', 'Loan_Amount_Requested',
       'Loan_Term', 'Loan_Purpose', 'Interest_Rate', 'Loan_Type',
       'Co-Applicant', 'Bank_Account_History', 'Transaction_Frequency',
       'Default_Risk', 'Loan_Approval_Status'],
      dtype='str')

In [13]:
df = df.drop("Applicant_ID", axis=1)

In [14]:
df

,Gender,Age,Marital_Status,Dependents,Education,Employment_Status,Occupation_Type,Residential_Status,City/Town,Annual_Income,...,Loan_Amount_Requested,Loan_Term,Loan_Purpose,Interest_Rate,Loan_Type,Co-Applicant,Bank_Account_History,Transaction_Frequency,Default_Risk,Loan_Approval_Status
0,Female,25,Married,2,Graduate,Employed,Business,Own,Urban,139901,...,24535,209,Home,4.27,Secured,Yes,8,20,0.81,1
1,Male,36,Married,2,High School,Employed,Business,Own,Suburban,21162,...,8288,33,Home,14.78,Unsecured,Yes,9,9,0.17,0
2,Male,43,Single,0,Postgraduate,Self-Employed,Freelancer,Own,Urban,27815,...,10308,159,Vehicle,12.33,Secured,Yes,7,27,0.25,0
3,Female,28,Married,0,High School,Self-Employed,Freelancer,Rent,Suburban,137853,...,33937,39,Personal,8.77,Secured,No,9,16,0.27,1
4,Female,32,Single,0,Graduate,Employed,Salaried,Rent,Suburban,81753,...,23360,34,Home,9.04,Unsecured,No,1,17,0.32,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51995,Female,47,Divorced,1,High School,Self-Employed,Professional,Own,Urban,56085,...,15723,60,Home,12.52,Secured,Yes,2,26,0.61,1
51996,Male,25,Married,3,High School,Self-Employed,Freelancer,Rent,Urban,79062,...,21209,237,Vehicle,5.21,Unsecured,No,8,26,0.04,1
51997,Female,48,Married,0,High School,Unemployed,Business,Rent,Urban,57471,...,10540,60,Education,10.60,Unsecured,No,8,24,0.31,0
51998,Female,48,Divorced,1,High School,Employed,Business,Own,Urban,49495,...,16765,32,Vehicle,8.11,Secured,Yes,3,12,0.34,0
51999,Female,38,Single,2,High School,Self-Employed,Freelancer,Own,Urban,90371,...,20454,93,Education,11.57,Unsecured,Yes,3,25,0.34,1

In [15]:
df.select_dtypes(include="object").columns

C:\Users\thara\AppData\Local\Temp\ipykernel_9480\1196084386.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").columns

Index(['Gender', 'Marital_Status', 'Education', 'Employment_Status',
       'Occupation_Type', 'Residential_Status', 'City/Town', 'Loan_Purpose',
       'Loan_Type', 'Co-Applicant'],
      dtype='str')

In [16]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Gender"] = le.fit_transform(df["Gender"])
df["Marital_Status"] = le.fit_transform(df["Marital_Status"])
df["Co-Applicant"] = le.fit_transform(df["Co-Applicant"])

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 52000 entries, 0 to 51999
Data columns (total 26 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Gender                      52000 non-null  int64
 1   Age                         52000 non-null  int64
 2   Marital_Status              52000 non-null  int64
 3   Dependents                  52000 non-null  int64
 4   Education                   52000 non-null  str
 5   Employment_Status           52000 non-null  str
 6   Occupation_Type             52000 non-null  str
 7   Residential_Status          52000 non-null  str
 8   City/Town                   52000 non-null  str
 9   Annual_Income               52000 non-null  int64
 10  Monthly_Expenses            52000 non-null  int64
 11  Credit_Score                52000 non-null  int64
 12  Existing_Loans              52000 non-null  int64
 13  Total_Existing_Loan_Amount  52000 non-null  int64
 14  Outstanding_Debt            52000 non-null  int64
 15  Loan_History                52000 non-null  int64
 16  Loan_Amount_Requested       52000 non-null  int64
 17  Loan_Term                   52000 non-null  int64
 18  Loan_Purpose                52000 non-null  str
 19  Interest_Rate               52000 non-null  float64
 20  Loan_Type                   52000 non-null  str
 21  Co-Applicant                52000 non-null  int64
 22  Bank_Account_History        52000 non-null  int64
 23  Transaction_Frequency       52000 non-null  int64
 24  Default_Risk                52000 non-null  float64
 25  Loan_Approval_Status        52000 non-null  int64
dtypes: float64(2), int64(17), str(7)
memory usage: 13.0 MB

In [18]:
df = pd.get_dummies(
    df,
    columns=[
        "Education",
        "Employment_Status",
        "Occupation_Type",
        "Residential_Status",
        "City/Town",
        "Loan_Purpose",
        "Loan_Type"
    ],
    drop_first=True
)

In [19]:
df

,Gender,Age,Marital_Status,Dependents,Annual_Income,Monthly_Expenses,Credit_Score,Existing_Loans,Total_Existing_Loan_Amount,Outstanding_Debt,...,Occupation_Type_Professional,Occupation_Type_Salaried,Residential_Status_Own,Residential_Status_Rent,City/Town_Suburban,City/Town_Urban,Loan_Purpose_Home,Loan_Purpose_Personal,Loan_Purpose_Vehicle,Loan_Type_Unsecured
0,0,25,1,2,139901,2533,743,0,10942,19822,...,False,False,True,False,False,True,True,False,False,False
1,1,36,1,2,21162,4041,468,1,48731,18321,...,False,False,True,False,True,False,True,False,False,True
2,1,43,2,0,27815,3453,389,2,6925,13851,...,False,False,True,False,False,True,False,False,True,False
3,0,28,1,0,137853,2732,778,0,42016,28608,...,False,False,False,True,True,False,False,True,False,False
4,0,32,2,0,81753,1648,752,2,31747,8780,...,False,True,False,True,True,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51995,0,47,0,1,56085,1794,381,0,3338,11909,...,True,False,True,False,False,True,True,False,False,False
51996,1,25,1,3,79062,1371,726,1,23659,24696,...,False,False,False,True,False,True,False,False,True,True
51997,0,48,1,0,57471,3442,396,2,4389,12367,...,False,False,False,True,False,True,False,False,False,True
51998,0,48,0,1,49495,2874,362,0,25518,13240,...,False,False,True,False,False,True,False,False,True,False
51999,0,38,2,2,90371,4152,803,1,5050,11009,...,False,False,True,False,False,True,False,False,False,True

In [20]:
df.shape

(52000, 34)

In [21]:
df.columns

Index(['Gender', 'Age', 'Marital_Status', 'Dependents', 'Annual_Income',
       'Monthly_Expenses', 'Credit_Score', 'Existing_Loans',
       'Total_Existing_Loan_Amount', 'Outstanding_Debt', 'Loan_History',
       'Loan_Amount_Requested', 'Loan_Term', 'Interest_Rate', 'Co-Applicant',
       'Bank_Account_History', 'Transaction_Frequency', 'Default_Risk',
       'Loan_Approval_Status', 'Education_High School',
       'Education_Postgraduate', 'Employment_Status_Self-Employed',
       'Employment_Status_Unemployed', 'Occupation_Type_Freelancer',
       'Occupation_Type_Professional', 'Occupation_Type_Salaried',
       'Residential_Status_Own', 'Residential_Status_Rent',
       'City/Town_Suburban', 'City/Town_Urban', 'Loan_Purpose_Home',
       'Loan_Purpose_Personal', 'Loan_Purpose_Vehicle', 'Loan_Type_Unsecured'],
      dtype='str')

In [22]:
df.select_dtypes(include="object").columns

Index([], dtype='str')

In [23]:
df["Annual_Income"].describe()
Q1 = df["Annual_Income"].quantile(0.25)
Q3 = df["Annual_Income"].quantile(0.75)

IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
outliers = df[(df["Annual_Income"] < lower) | (df["Annual_Income"] > upper)]

print(len(outliers))

0

In [24]:
num_cols = df.select_dtypes(include=["int64","float64"]).columns

for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    outliers = df[(df[col] < lower) | (df[col] > upper)]
    
    print(col, len(outliers))

Gender 0
Age 862
Marital_Status 0
Dependents 0
Annual_Income 0
Monthly_Expenses 0
Credit_Score 0
Existing_Loans 0
Total_Existing_Loan_Amount 0
Outstanding_Debt 0
Loan_History 10327
Loan_Amount_Requested 896
Loan_Term 0
Interest_Rate 0
Co-Applicant 0
Bank_Account_History 0
Transaction_Frequency 0
Default_Risk 0
Loan_Approval_Status 0

In [25]:
df["Age"].describe()

count    52000.000000
mean        38.898385
std         10.553928
min         18.000000
25%         31.000000
50%         38.000000
75%         45.000000
max         69.000000
Name: Age, dtype: float64

In [26]:
X = df.drop("Loan_Approval_Status", axis=1)
y = df["Loan_Approval_Status"]

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=42
)

In [28]:
df["Debt_to_Income_Ratio"] = df["Outstanding_Debt"] / df["Annual_Income"]

In [29]:
df["Debt_to_Income_Ratio"]

0        0.141686
1        0.865750
2        0.497969
3        0.207525
4        0.107397
           ...
51995    0.212338
51996    0.312362
51997    0.215187
51998    0.267502
51999    0.121820
Name: Debt_to_Income_Ratio, Length: 52000, dtype: float64

In [30]:
df.drop("Debt_to_Income_Ratio", axis=1, inplace=True)

In [31]:
df.columns

Index(['Gender', 'Age', 'Marital_Status', 'Dependents', 'Annual_Income',
       'Monthly_Expenses', 'Credit_Score', 'Existing_Loans',
       'Total_Existing_Loan_Amount', 'Outstanding_Debt', 'Loan_History',
       'Loan_Amount_Requested', 'Loan_Term', 'Interest_Rate', 'Co-Applicant',
       'Bank_Account_History', 'Transaction_Frequency', 'Default_Risk',
       'Loan_Approval_Status', 'Education_High School',
       'Education_Postgraduate', 'Employment_Status_Self-Employed',
       'Employment_Status_Unemployed', 'Occupation_Type_Freelancer',
       'Occupation_Type_Professional', 'Occupation_Type_Salaried',
       'Residential_Status_Own', 'Residential_Status_Rent',
       'City/Town_Suburban', 'City/Town_Urban', 'Loan_Purpose_Home',
       'Loan_Purpose_Personal', 'Loan_Purpose_Vehicle', 'Loan_Type_Unsecured'],
      dtype='str')

Types of models trained here

    -->Logistic Regression

    -->Decision Tree

    -->Random Forest
    
    -->Gradient Boosting

In [32]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

model = LogisticRegression(max_iter=1000)
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)


accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)



print(classification_report(y_test, y_pred))

Accuracy: 0.8541538461538462
              precision    recall  f1-score   support

           0       0.85      0.70      0.77      4550
           1       0.85      0.93      0.89      8450

    accuracy                           0.85     13000
   macro avg       0.85      0.82      0.83     13000
weighted avg       0.85      0.85      0.85     13000

In [34]:
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)
accuracy_dt = accuracy_score(y_test, y_pred_dt)
print("Decision Tree Accuracy:", accuracy_dt)
print(classification_report(y_test, y_pred_dt))

Decision Tree Accuracy: 0.7330769230769231
              precision    recall  f1-score   support

           0       0.61      0.65      0.63      4550
           1       0.80      0.78      0.79      8450

    accuracy                           0.73     13000
   macro avg       0.71      0.71      0.71     13000
weighted avg       0.74      0.73      0.73     13000

In [35]:
from sklearn.ensemble import RandomForestClassifier


rf_model = RandomForestClassifier(n_estimators=100, random_state=42)


rf_model.fit(X_train, y_train)


y_pred_rf = rf_model.predict(X_test)


print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_rf))

Accuracy: 0.8546923076923076

Classification Report:

              precision    recall  f1-score   support

           0       0.85      0.71      0.77      4550
           1       0.86      0.93      0.89      8450

    accuracy                           0.85     13000
   macro avg       0.85      0.82      0.83     13000
weighted avg       0.85      0.85      0.85     13000

In [36]:
from sklearn.svm import SVC

svm_model = SVC(kernel="rbf", random_state=42)
svm_model.fit(X_train_scaled, y_train)

y_pred_svm = svm_model.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred_svm))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_svm))

Accuracy: 0.8524615384615385

Classification Report:

              precision    recall  f1-score   support

           0       0.85      0.70      0.77      4550
           1       0.85      0.93      0.89      8450

    accuracy                           0.85     13000
   macro avg       0.85      0.82      0.83     13000
weighted avg       0.85      0.85      0.85     13000

In [37]:
from sklearn.ensemble import GradientBoostingClassifier

gb_model = GradientBoostingClassifier()
gb_model.fit(X_train, y_train)

y_pred_gb = gb_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_gb))
print(classification_report(y_test, y_pred_gb))

Accuracy: 0.8543846153846154
              precision    recall  f1-score   support

           0       0.85      0.71      0.77      4550
           1       0.86      0.93      0.89      8450

    accuracy                           0.85     13000
   macro avg       0.85      0.82      0.83     13000
weighted avg       0.85      0.85      0.85     13000

In [40]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

xgb_model = XGBClassifier(eval_metric="logloss")

xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_xgb))

Accuracy: 0.8522307692307692

In [41]:
from lightgbm import LGBMClassifier

lgb_model = LGBMClassifier(random_state=42)
lgb_model.fit(X_train, y_train)
y_pred_lgb = lgb_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_lgb))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_lgb))

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 24916, number of negative: 14084
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001794 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2245
[LightGBM] [Info] Number of data points in the train set: 39000, number of used features: 33
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.638872 -> initscore=0.570471
[LightGBM] [Info] Start training from score 0.570471
Accuracy: 0.8546923076923076

Classification Report:

              precision    recall  f1-score   support

           0       0.85      0.71      0.77      4550
           1       0.86      0.93      0.89      8450

    accuracy                           0.85     13000
   macro avg       0.85      0.82      0.83     13000
weighted avg       0.85      0.85      0.85     13000

In [42]:
\

results = {
    "Logistic Regression": accuracy_score(y_test, y_pred),
    "SVM": accuracy_score(y_test, y_pred_svm),
    "Decision Tree": accuracy_score(y_test, y_pred_dt),
    "Random Forest": accuracy_score(y_test, y_pred_rf),
    "Gradient Boosting": accuracy_score(y_test, y_pred_gb),
    "XGBoost": accuracy_score(y_test, y_pred_xgb),
    "LightGBM": accuracy_score(y_test, y_pred_lgb)
}

results_df = pd.DataFrame(results.items(), columns=["Model", "Accuracy"])
results_df = results_df.sort_values(by="Accuracy", ascending=False)

print(results_df)

                 Model  Accuracy
3        Random Forest  0.854692
6             LightGBM  0.854692
4    Gradient Boosting  0.854385
0  Logistic Regression  0.854154
1                  SVM  0.852462
5              XGBoost  0.852231
2        Decision Tree  0.733077

In [43]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

[[3216 1334]
 [ 555 7895]]
              precision    recall  f1-score   support

           0       0.85      0.71      0.77      4550
           1       0.86      0.93      0.89      8450

    accuracy                           0.85     13000
   macro avg       0.85      0.82      0.83     13000
weighted avg       0.85      0.85      0.85     13000

In [44]:
import pandas as pd

importance = rf_model.feature_importances_

feature_importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": importance
}).sort_values(by="Importance", ascending=False)

print(feature_importance.head(10))

                       Feature  Importance
6                 Credit_Score    0.242074
11       Loan_Amount_Requested    0.178358
4                Annual_Income    0.108924
1                          Age    0.054537
9             Outstanding_Debt    0.041344
5             Monthly_Expenses    0.041167
13               Interest_Rate    0.041165
8   Total_Existing_Loan_Amount    0.041159
12                   Loan_Term    0.038221
17                Default_Risk    0.035730

In [47]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier

param_dist = {
    "n_estimators": [100, 200, 300],
    "max_depth": [None, 10, 20, 30],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4]
}

rf = RandomForestClassifier(random_state=42)

random_search = RandomizedSearchCV(
    rf,
    param_distributions=param_dist,
    n_iter=10,
    cv=3,
    n_jobs=-1,
    random_state=42
)

random_search.fit(X_train, y_train)

print("Best Parameters:", random_search.best_params_)

Best Parameters: {'n_estimators': 300, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_depth': 20}

In [48]:
final_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=20,
    min_samples_split=5,
    min_samples_leaf=4,
    random_state=42
)

final_model.fit(X_train, y_train)

RandomForestClassifier(max_depth=20, min_samples_leaf=4, min_samples_split=5,
                       n_estimators=300, random_state=42)

In [52]:
import os
import pickle


os.makedirs("model", exist_ok=True)

pickle.dump(final_model, open("model/random_forest_model.pkl", "wb"))

pickle.dump(X_train.columns, open("model/model_columns.pkl", "wb"))

In [55]:
import pickle
import pandas as pd


model = pickle.load(open("model/random_forest_model.pkl", "rb"))
model_columns = pickle.load(open("model/model_columns.pkl", "rb"))

def predict_loan(data):
    
    
    df = pd.DataFrame([data])
    
    
    df = pd.get_dummies(df)
    
    
    df = df.reindex(columns=model_columns, fill_value=0)
    
    
    prediction = model.predict(df)
    
    return int(prediction[0])

In [56]:
input_data = {
    "Age": 35,
    "Annual_Income": 50000,
    "Loan_Amount_Requested": 12000,
    "Credit_Score": 720
}

result = predict_loan(input_data)

print("Prediction:", result)

Prediction: 0

In [63]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [64]:
from src.predict import predict_loan

In [65]:
import sys
import os

sys.path.append(os.path.abspath(".."))

from src.predict import predict_loan

sample = {
    "Age": 35,
    "Annual_Income": 60000,
    "Credit_Score": 720,
    "Loan_Amount_Requested": 15000
}

result = predict_loan(sample)

print("Prediction:", result)

Prediction: 0

In [66]:
sample1 = {
    "Age": 25,
    "Annual_Income": 40000,
    "Credit_Score": 650,
    "Loan_Amount_Requested": 10000
}

sample2 = {
    "Age": 45,
    "Annual_Income": 120000,
    "Credit_Score": 780,
    "Loan_Amount_Requested": 20000
}

print(predict_loan(sample1))
print(predict_loan(sample2))

0
1

In [ ]:
import os
import pickle


os.makedirs("../model", exist_ok=True)


pickle.dump(final_model, open("../model/random_forest_model.pkl", "wb"))


pickle.dump(X_train.columns, open("../model/model_columns.pkl", "wb"))

In [ ]:
final_model.predict(X_test[:100])

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1])